apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  clusterIP: 172.20.1.10
  selector:
    app: shipping-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-app
spec:
  selector:
    matchLabels:
      app: shipping-app
  replicas: 1
  template:
    metadata:
      labels:
        app: shipping-app
    spec:
      containers:
      - name: shipping-app
        image: ignaciomontero2022/shipping-service-example:lasted
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1000Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080